# Generated by Django 6.0 on 2025-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.BigAutoField(db_column='clientid', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('avatar', models.CharField(default='idle.png', max_length=2048)),
                ('role', models.CharField(choices=[('No Commerce', 'No Commerce'), ('Developer', 'Developer'), ('Manager', 'Manager'), ('Lead', 'Lead'), ('Individual', 'Individual')], max_length=30)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.BigAutoField(db_column='eventid', primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('Extreme', 'Extreme'), ('High', 'High'), ('Average', 'Average'), ('Low', 'Low')], max_length=7)),
                ('theme', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('link', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventHandler',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'eventhandler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('medialinkid', models.BigAutoField(db_column='medialinkid', primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2048)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medialink',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.BigAutoField(db_column='messageid', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.BigAutoField(db_column='projectid', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='To Do', max_length=20)),
                ('medialink', models.CharField(blank=True, max_length=2048, null=True)),
                ('creationdate', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectHandler',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'projecthandler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.BigAutoField(db_column='taskid', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Extreme', 'Extreme'), ('High', 'High'), ('Average', 'Average'), ('Low', 'Low')], max_length=7)),
                ('description', models.CharField(max_length=1500)),
                ('creationdate', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='To Do', max_length=20)),
                ('resultlink', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskHandler',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'taskhandler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.BigAutoField(db_column='teamid', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamHandler',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teamhandler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnderTask',
            fields=[
                ('undertaskid', models.BigAutoField(db_column='undertaskid', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('creationdate', models.DateField(auto_now_add=True)),
                ('completiondate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='To Do', max_length=20)),
                ('resultlink', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'undertask',
                'managed': False,
            },
        ),
    ]
